- name: "Install neovim and ctags"
  ansible.builtin.apt:
    name:
      - "neovim>=0.10*"
      - "exuberant-ctags"
    state: "present"
  become: true

- name: "Ensure .config directory exists"
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    mode: '0755'

- name: "Ensure config file link exists"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../configs/nvim"
    dest: "~/.config/nvim"
    state: link
